### PR TITLE
Possible 2.1

### PR DESCRIPTION
**Pull request by adam-h**
This includes the sortStart event from Steel and ghost going home fixes fixes.

We are using these live (along with another minor ghost tweak).

@steel @thoughtless @nguyenj Anything against merging this in? Repo could generally use a cleanup, and we are still a little diverged, but that can come later

### CODE REVIEW

**Comment by thoughtless** [comment]
I don't really have time to review this soon. As long as the changes are
tested thoroughly across the devices we want to support, I'm fine with just
about any changes. I have found that the Microsoft Surface is the device
with the most gotchas.

I also would strongly prefer having something in the examples directory for
each feature.

**Comment by steel** [comment]
I have 1 more patch to go in shortly.

**Comment by steel** [comment]
I also updated my PR https://github.com/polleverywhere/sordid-dragon/pull/4

**Comment by steel** [comment]
We should also address the safari drop target issue too

**Comment by nguyenj** [comment]
Should I try and merge my [PR 3](https://github.com/polleverywhere/sordid-dragon/pull/3) into this?

**Comment by steel** [comment]
@nguyenj yea probably a good idea

**Comment by steel** [comment]
@adam-h I recommend you move your commit on to a new branch off master. We've merged the other commits already into master individually. I have 1 commit unpublished so feel free to publish that after you've merged.

**Comment by adam-h** [comment]
Done and in master

**Pull request closed without merging**
